# Generated by Django 5.1.1 on 2024-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Токен"
            ),
        ),
    ]
