# Generated by Django 5.1.1 on 2024-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_options_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
