# Generated by Django 5.1.1 on 2024-09-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="заголовок"),
        ),
    ]
