# Generated by Django 5.1.1 on 2024-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
