# Generated by Django 5.1.1 on 2024-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "-price", "created_at", "-updated_at"],
                "permissions": [
                    ("can_unpublish_product", "Может отменить публикацию продукта"),
                    ("can_change_description", "Может изменить описание продукта"),
                    ("can_change_category", "Может изменить категорию продукта"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
    ]
